"""MenuItem rectification: stores the index of the section (in the menu list) instead of section name

Revision ID: 299ec9675e6b
Revises: b97300e3f2fa
Create Date: 2026-06-16 11:57:01.077142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299ec9675e6b'
down_revision: Union[str, Sequence[str], None] = 'b97300e3f2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('group_index', sa.Integer(), nullable=False))
    op.add_column('menu_items', sa.Column('sort_index', sa.Integer(), nullable=False))
    op.drop_column('menu_items', 'sorted_by')
    op.drop_column('menu_items', 'grouped_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('grouped_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('menu_items', sa.Column('sorted_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('menu_items', 'sort_index')
    op.drop_column('menu_items', 'group_index')
    # ### end Alembic commands ###
