"""Tables creation

Revision ID: b97300e3f2fa
Revises: 
Create Date: 2026-06-16 10:24:27.838693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97300e3f2fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name_fr', sa.String(length=64), nullable=False),
    sa.Column('name_nl', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('restaurant', sa.String(length=64), nullable=False),
    sa.Column('has_allergen', sa.Boolean(), nullable=False),
    sa.Column('is_signature', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=32), nullable=False),
    sa.Column('value_fr', sa.String(length=32), nullable=False),
    sa.Column('value_nl', sa.String(length=32), nullable=False),
    sa.Column('label_fr', sa.String(length=64), nullable=False),
    sa.Column('label_nl', sa.String(length=64), nullable=False),
    sa.Column('negative', sa.Boolean(), nullable=False),
    sa.Column('dish_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_categories',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('profitability_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'category_id')
    )
    op.create_table('menu_items',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('grouped_by', sa.String(length=64), nullable=False),
    sa.Column('sorted_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['menus.date'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('date', 'dish_id')
    )
    op.create_table('menu_sections',
    sa.Column('menu_id', sa.Date(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.date'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_sections')
    op.drop_table('menu_items')
    op.drop_table('dish_categories')
    op.drop_table('sections')
    op.drop_table('menus')
    op.drop_table('dishes')
    op.drop_table('categories')
    # ### end Alembic commands ###
